dist: xenial
language: python
arch:
  - arm64
  - amd64
python:
  - "3.6"
  - "3.7"
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $(tox -l | grep $TOX_PYTHON_VERSION | paste -sd "," -)
after_success:
  - coveralls
sudo: false
