dist: xenial
language: python
arch:
  - arm64
  - amd64
python:
  - "3.8"
install:
  - pip install tox
  - pip install python-coveralls
script:
  #- TOX_PYTHON_VERSION=$(if [ $TRAVIS_PYTHON_VERSION = "pypy" ]; then echo "pypy"; else echo py$TRAVIS_PYTHON_VERSION | tr -d .; fi)
  - tox -e $(tox -l | grep $TOX_PYTHON_VERSION | paste -sd "," -)
  - echo $TOX_PYTHON_VERSION
after_success:
  - coveralls
sudo: false
